;; CODIGO PARA TESTAR OS FLAGS
.CODE
	LDLI R1,#FDH
	LDHI R1,#FFH ;;ATIVA NEGATIVO
	LDLI R2,#FEH
	LDHI R2,#FFH ;;ATIVA NEGATIVO
	ADD R3,R1,R2 ;;ATIVA CARRY E NEGATIVO 
	LDLI R4,#00H ;;ATIVA ZERO
	LDHI R4,#80H ;;ATIVA NEGATIVO
	LDLI R5,#FFH
	LDHI R5,#FFH ;;ATIVA NEGATIVO
	ADD R6,R4,R5 ;;ATIVA CARRY E OVERFLOW
	LDLI R7,#FFH 
	LDHI R7,#7FH
	LDLI R8,#00H ;;ATIVA ZERO
	LDHI R8,#01H
	ADD R9,R7,R8 ;;ATIVA OVERFLOW E NEGATIVO
	HALT
.ENDCODE